{
    "Information": {
        "Category": null, 
        "CAPEC": null, 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-1634", 
                "published": "2010-05-27T15:30:01.767-04:00", 
                "id": "CVE-2010-1634", 
                "modified": "2013-05-14T23:08:53.080-04:00", 
                "summary": "Multiple integer overflows in audioop.c in the audioop module in Python 2.6, 2.7, 3.1, and 3.2 allow context-dependent attackers to cause a denial of service (application crash) via a large fragment, as demonstrated by a call to audioop.lin2lin with a long string in the first argument, leading to a buffer overflow.  NOTE: this vulnerability exists because of an incorrect fix for CVE-2008-3143.5."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/189.html", 
                "id": "CWE-189", 
                "title": "Numeric Errors"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:python:python:3.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.7"
            }, 
            {
                "id": "cpe:/a:python:python:3.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.6"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.53381", 
                "id": 53381
            }
        ], 
        "IAVM": [
            {
                "Disa key": "V0031252", 
                "id": "2012-A-0020", 
                "title": "Multiple Vulnerabilities in VMware ESX 4.1 and ESXi 4.1"
            }
        ], 
        "BID": [
            {
                "url": "http://www.securityfocus.com/bid/40370", 
                "id": 40370
            }
        ], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://svn.python.org/view?rev=81079&view=rev", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://svn.python.org/view?rev=81045&view=rev", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://bugs.python.org/issue8674", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2011/0212", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2011/0122", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2010/1448", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1616-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.securityfocus.com/bid/40370", 
                    "vendor": "BID"
                }, 
                {
                    "url": "http://www.redhat.com/support/errata/RHSA-2011-0027.html", 
                    "vendor": "REDHAT"
                }, 
                {
                    "url": "http://support.apple.com/kb/HT5002", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://secunia.com/advisories/51087", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/51040", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/51024", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/50858", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/43068", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/42888", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/40194", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/39937", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html", 
                    "vendor": "SUSE"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html", 
                    "vendor": "SUSE"
                }, 
                {
                    "url": "http://lists.fedoraproject.org/pipermail/package-announce/2010-June/042751.html", 
                    "vendor": "FEDORA"
                }, 
                {
                    "url": "http://lists.apple.com/archives/Security-announce/2011//Oct/msg00003.html", 
                    "vendor": "APPLE"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "2.9", 
                    "access complexity": "low", 
                    "confidentiality impact": "none", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "5.0", 
                    "integrity impact": "none", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2010-1634"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:17830", 
                "title": "USN-1613-1 -- python2.5 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:17830"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28118", 
                "title": "DEPRECATED: ELSA-2011-0027 -- python security, bug fix, and enhancement update (low)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28118"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:17941", 
                "title": "USN-1616-1 -- python3.1 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:17941"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:22821", 
                "title": "ELSA-2011:0027: python security, bug fix, and enhancement update (Low)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:22821"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21921", 
                "title": "RHSA-2011:0027: python security, bug fix, and enhancement update (Low)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21921"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18020", 
                "title": "USN-1613-2 -- python2.4 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18020"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18043", 
                "title": "USN-1596-1 -- python2.6 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18043"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "CentOS Update for python CESA-2011:0491 centos4 i386", 
                "file": "gb_CESA-2011_0491_python_centos4_i386.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "880556"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0491 centos4 x86_64", 
                "file": "gb_CESA-2011_0491_python_centos4_x86_64.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "881427"
            }, 
            {
                "name": "Fedora Update for python3 FEDORA-2010-13388", 
                "file": "gb_fedora_2010_13388_python3_fc13.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "862373"
            }, 
            {
                "name": "Fedora Update for python FEDORA-2010-9565", 
                "file": "gb_fedora_2010_9565_python_fc12.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "862218"
            }, 
            {
                "name": "Fedora Update for python FEDORA-2010-9652", 
                "file": "gb_fedora_2010_9652_python_fc13.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "862160"
            }, 
            {
                "name": "Mac OS X v10.6.8 Multiple Vulnerabilities (2011-006)", 
                "file": "gb_macosx_su11-006.nasl", 
                "family": "Mac OS X Local Security Checks", 
                "id": "802336"
            }, 
            {
                "name": "Mandriva Update for plymouth MDVA-2010:132 (plymouth)", 
                "file": "gb_mandriva_MDVA_2010_132.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "831023"
            }, 
            {
                "name": "Mandriva Update for python MDVSA-2010:132 (python)", 
                "file": "gb_mandriva_MDVSA_2010_132.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "831110"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0027-01", 
                "file": "gb_RHSA-2011_0027-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870377"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0491-01", 
                "file": "gb_RHSA-2011_0491-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870430"
            }, 
            {
                "name": "Ubuntu Update for python2.6 USN-1596-1", 
                "file": "gb_ubuntu_USN_1596_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841178"
            }, 
            {
                "name": "Ubuntu Update for python2.5 USN-1613-1", 
                "file": "gb_ubuntu_USN_1613_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841195"
            }, 
            {
                "name": "Ubuntu Update for python2.4 USN-1613-2", 
                "file": "gb_ubuntu_USN_1613_2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841194"
            }, 
            {
                "name": "Ubuntu Update for python3.1 USN-1616-1", 
                "file": "gb_ubuntu_USN_1616_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841199"
            }, 
            {
                "name": "VMSA-2012-0001 VMware ESXi and ESX updates to third party library and ESX Service Console", 
                "file": "gb_VMSA-2012-0001.nasl", 
                "family": "VMware Local Security Checks", 
                "id": "103448"
            }
        ], 
        "Nessus": [
            {
                "name": "CentOS 4 : python (CESA-2011:0491)", 
                "file": "centos_RHSA-2011-0491.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "53814"
            }, 
            {
                "name": "Fedora 13 : python3-3.1.2-7.fc13 (2010-13388)", 
                "file": "fedora_2010-13388.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "49107"
            }, 
            {
                "name": "Fedora 12 : python-2.6.2-8.fc12 (2010-9565)", 
                "file": "fedora_2010-9565.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "47600"
            }, 
            {
                "name": "Fedora 13 : python-2.6.4-27.fc13 (2010-9652)", 
                "file": "fedora_2010-9652.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "47547"
            }, 
            {
                "name": "GLSA-201401-04 : Python: Multiple vulnerabilities", 
                "file": "gentoo_GLSA-201401-04.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "71811"
            }, 
            {
                "name": "Mac OS X 10.7 < 10.7.2", 
                "file": "macosx_10_7_2.nasl", 
                "family": "MacOS X Local Security Checks", 
                "id": "56480"
            }, 
            {
                "name": "Mac OS X Multiple Vulnerabilities (Security Update 2011-006)", 
                "file": "macosx_SecUpd2011-006.nasl", 
                "family": "MacOS X Local Security Checks", 
                "id": "56481"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2010:132)", 
                "file": "mandriva_MDVSA-2010-132.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "48191"
            }, 
            {
                "name": "Oracle Linux 4 : python (ELSA-2011-0491)", 
                "file": "oraclelinux_ELSA-2011-0491.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "68270"
            }, 
            {
                "name": "RHEL 5 : python (RHSA-2011:0027)", 
                "file": "redhat-RHSA-2011-0027.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "51524"
            }, 
            {
                "name": "RHEL 4 : python (RHSA-2011:0491)", 
                "file": "redhat-RHSA-2011-0491.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "53820"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL5.x i386/x86_64", 
                "file": "sl_20110113_python_on_SL5_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "60935"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL4.x, SL5.x i386/x86_64", 
                "file": "sl_20110505_python_on_SL4_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "61033"
            }, 
            {
                "name": "Oracle Solaris Third-Party Patch Update : python (cve_2010_1634_integer_overflow)", 
                "file": "solaris11_python_20130313.nasl", 
                "family": "Solaris Local Security Checks", 
                "id": "80748"
            }, 
            {
                "name": "openSUSE Security Update : libpython2_6-1_0 (openSUSE-SU-2010:1049-1)", 
                "file": "suse_11_2_libpython2_6-1_0-101028.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "53756"
            }, 
            {
                "name": "SuSE 11 Security Update : Python (SAT Patch Number 3491)", 
                "file": "suse_11_libpython2_6-1_0-101028.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "51134"
            }, 
            {
                "name": "SuSE 11.1 Security Update : Python (SAT Patch Number 3493)", 
                "file": "suse_11_libpython2_6-1_0-101109.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "51623"
            }, 
            {
                "name": "SuSE 10 Security Update : Python (ZYPP Patch Number 7314)", 
                "file": "suse_python-7314.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "51642"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 11.04 / 11.10 : python2.6 vulnerabilities (USN-1596-1)", 
                "file": "ubuntu_USN-1596-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62436"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.5 vulnerabilities (USN-1613-1)", 
                "file": "ubuntu_USN-1613-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62619"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.4 vulnerabilities (USN-1613-2)", 
                "file": "ubuntu_USN-1613-2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62620"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 11.04 : python3.1 vulnerabilities (USN-1616-1)", 
                "file": "ubuntu_USN-1616-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62700"
            }, 
            {
                "name": "ESXi 5.0 < Build 608089 Multiple Vulnerabilities (remote check)", 
                "file": "vmware_esxi_5_0_build_608089_remote.nasl", 
                "family": "Misc.", 
                "id": "70881"
            }, 
            {
                "name": "VMSA-2012-0001 : VMware ESXi and ESX updates to third-party library and ESX Service Console", 
                "file": "vmware_VMSA-2012-0001.nasl", 
                "family": "VMware ESX Local Security Checks", 
                "id": "57749"
            }, 
            {
                "name": "VMware ESX / ESXi Service Console and Third-Party Libraries Multiple Vulnerabilities (VMSA-2012-0001) (remote check)", 
                "file": "vmware_VMSA-2012-0001_remote.nasl", 
                "family": "Misc.", 
                "id": "89105"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [
            {
                "url": "https://admin.fedoraproject.org/updates/FEDORA-2010-9652", 
                "id": "FEDORA-2010-9652"
            }
        ], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [
            {
                "url": "https://www.suse.com/security/cve/CVE-2010-1634.html", 
                "id": "SUSE-SR:2010:024"
            }, 
            {
                "url": "https://www.suse.com/security/cve/CVE-2010-1634.html", 
                "id": "SUSE-SR:2011:002"
            }
        ], 
        "Redhat": [
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110027", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0027.html", 
                    "id": "RHSA-2011:0027", 
                    "title": "RHSA-2011:0027: python security, bug fix, and enhancement update (Low)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=482814", 
                    "title": "CVE-2008-5983 python: untrusted python modules search path", 
                    "id": "482814", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=541698", 
                    "title": "CVE-2009-4134 CVE-2010-1449 CVE-2010-1450 python: rgbimg: multiple security issues", 
                    "id": "541698", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=569093", 
                    "title": "Python 2.4's arena allocator does not release memory back to the system, leading to \"high-water mark\" memory usage", 
                    "id": "569093", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690", 
                    "title": "CVE-2010-1634 python: audioop: incorrect integer overflow checks", 
                    "id": "590690", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=598197", 
                    "title": "CVE-2010-2089 Python: Memory corruption in audioop module", 
                    "id": "598197", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=609017", 
                    "title": "subprocess leaves open fds on construction error", 
                    "id": "609017", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=609020", 
                    "title": "subprocess fails in select when descriptors are large", 
                    "id": "609020", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=625372", 
                    "title": "split python-libs subpackage", 
                    "id": "625372", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=644147", 
                    "title": "Patch for get_filename in email.message when content-disposition is missing", 
                    "id": "644147", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=644761", 
                    "title": "python-libs conflict on ia64 compatlayer", 
                    "id": "644761", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110491", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0491.html", 
                    "id": "RHSA-2011:0491", 
                    "title": "RHSA-2011:0491: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=531697", 
                    "title": "CVE-2009-3720 expat: buffer over-read and crash on XML with malformed UTF-8 sequences", 
                    "id": "531697", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690", 
                    "title": "CVE-2010-1634 python: audioop: incorrect integer overflow checks", 
                    "id": "590690", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=598197", 
                    "title": "CVE-2010-2089 Python: Memory corruption in audioop module", 
                    "id": "598197", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }
        ], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [
            {
                "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                "id": "USN-1596-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                "id": "USN-1613-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                "id": "USN-1613-2"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1616-1", 
                "id": "USN-1616-1"
            }
        ], 
        "Debian": [], 
        "Vmware": []
    }
}