{
    "Information": {
        "Category": [
            {
                "url": "https://cwe.mitre.org/data/definitions/867.html", 
                "id": "CWE-867", 
                "title": "2011 Top 25 - Weaknesses On the Cusp"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/801.html", 
                "id": "CWE-801", 
                "title": "2010 Top 25 - Insecure Interaction Between Components"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/691.html", 
                "id": "CWE-691", 
                "title": "Insufficient Control Flow Management"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/361.html", 
                "id": "CWE-361", 
                "title": "Time and State"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/743.html", 
                "id": "CWE-743", 
                "title": "CERT C Secure Coding Section 09 - Input Output (FIO)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/751.html", 
                "id": "CWE-751", 
                "title": "2009 Top 25 - Insecure Interaction Between Components"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/852.html", 
                "id": "CWE-852", 
                "title": "CERT Java Secure Coding Section 07 - Visibility and Atomicity (VNA)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/877.html", 
                "id": "CWE-877", 
                "title": "CERT C++ Secure Coding Section 09 - Input Output (FIO)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/882.html", 
                "id": "CWE-882", 
                "title": "CERT C++ Secure Coding Section 14 - Concurrency (CON)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/988.html", 
                "id": "CWE-988", 
                "title": "SFP Secondary Cluster: Race Condition Window"
            }
        ], 
        "CAPEC": [
            {
                "url": "https://capec.mitre.org/data/definitions/26.html", 
                "id": 26
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/29.html", 
                "id": 29
            }
        ], 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-3493", 
                "published": "2010-10-19T16:00:04.283-04:00", 
                "id": "CVE-2010-3493", 
                "modified": "2013-05-14T23:12:16.297-04:00", 
                "summary": "Multiple race conditions in smtpd.py in the smtpd module in Python 2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/362.html", 
                "id": "CWE-362", 
                "title": "Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:python:python:2.7"
            }, 
            {
                "id": "cpe:/a:python:python:2.6"
            }, 
            {
                "id": "cpe:/a:python:python:3.2:alpha"
            }, 
            {
                "id": "cpe:/a:python:python:3.1"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.55129", 
                "id": 55129
            }
        ], 
        "IAVM": [
            {
                "Disa key": "V0031252", 
                "id": "2012-A-0020", 
                "title": "Multiple Vulnerabilities in VMware ESX 4.1 and ESXi 4.1"
            }
        ], 
        "BID": [
            {
                "url": "http://www.securityfocus.com/bid/44533", 
                "id": 44533
            }
        ], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://bugs.python.org/issue9129", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://bugs.python.org/issue6706", 
                    "vendor": "MISC"
                }, 
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "https://bugs.launchpad.net/zodb/+bug/135108", 
                    "vendor": "MISC"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2011/0212", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.securityfocus.com/bid/44533", 
                    "vendor": "BID"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/24/3", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/22/3", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/11/2", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/09/6", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216", 
                    "vendor": "MANDRIVA"
                }, 
                {
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215", 
                    "vendor": "MANDRIVA"
                }, 
                {
                    "url": "http://svn.python.org/view?view=rev&revision=84289", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://secunia.com/advisories/51040", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/51024", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/50858", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/43068", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html", 
                    "vendor": "SUSE"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html", 
                    "vendor": "SUSE"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "2.9", 
                    "access complexity": "medium", 
                    "confidentiality impact": "none", 
                    "authentication": "none", 
                    "exploit": "8.6", 
                    "base": "4.3", 
                    "integrity impact": "none", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": [
                {
                    "id": "CWE-691", 
                    "title": "Insufficient Control Flow Management"
                }
            ], 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2010-3493"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:17830", 
                "title": "USN-1613-1 -- python2.5 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:17830"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:23229", 
                "title": "ELSA-2011:0492: python security update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:23229"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28060", 
                "title": "DEPRECATED: ELSA-2011-0492 -- python security update (moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28060"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28032", 
                "title": "DEPRECATED: ELSA-2011-0554 -- python security, bug fix, and enhancement update (moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28032"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:23473", 
                "title": "ELSA-2011:0554: python security, bug fix, and enhancement update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:23473"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:12210", 
                "title": "Vulnerability in smtpd module in Python 2.6, 2.7, 3.1 and 3.2 alpha", 
                "class": "vulnerability", 
                "id": "oval:org.mitre.oval:def:12210"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18020", 
                "title": "USN-1613-2 -- python2.4 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18020"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21923", 
                "title": "RHSA-2011:0492: python security update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21923"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21626", 
                "title": "RHSA-2011:0554: python security, bug fix, and enhancement update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21626"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:19755", 
                "title": "VMware ESXi and ESX updates to third party library and ESX Service Console", 
                "class": "vulnerability", 
                "id": "oval:org.mitre.oval:def:19755"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:15345", 
                "title": "USN-1314-1 -- Python 3 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:15345"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18043", 
                "title": "USN-1596-1 -- python2.6 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18043"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "CentOS Update for python CESA-2011:0491 centos4 i386", 
                "file": "gb_CESA-2011_0491_python_centos4_i386.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "880556"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0491 centos4 x86_64", 
                "file": "gb_CESA-2011_0491_python_centos4_x86_64.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "881427"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0492 centos5 i386", 
                "file": "gb_CESA-2011_0492_python_centos5_i386.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "880500"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0492 centos5 x86_64", 
                "file": "gb_CESA-2011_0492_python_centos5_x86_64.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "881282"
            }, 
            {
                "name": "Mandriva Update for python MDVSA-2010:215 (python)", 
                "file": "gb_mandriva_MDVSA_2010_215.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "831224"
            }, 
            {
                "name": "Mandriva Update for python MDVSA-2010:216 (python)", 
                "file": "gb_mandriva_MDVSA_2010_216.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "831233"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0491-01", 
                "file": "gb_RHSA-2011_0491-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870430"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0492-01", 
                "file": "gb_RHSA-2011_0492-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870428"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0554-01", 
                "file": "gb_RHSA-2011_0554-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870597"
            }, 
            {
                "name": "Ubuntu Update for python3.1 USN-1314-1", 
                "file": "gb_ubuntu_USN_1314_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "840852"
            }, 
            {
                "name": "Ubuntu Update for python2.6 USN-1596-1", 
                "file": "gb_ubuntu_USN_1596_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841178"
            }, 
            {
                "name": "Ubuntu Update for python2.5 USN-1613-1", 
                "file": "gb_ubuntu_USN_1613_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841195"
            }, 
            {
                "name": "Ubuntu Update for python2.4 USN-1613-2", 
                "file": "gb_ubuntu_USN_1613_2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841194"
            }, 
            {
                "name": "VMSA-2012-0001 VMware ESXi and ESX updates to third party library and ESX Service Console", 
                "file": "gb_VMSA-2012-0001.nasl", 
                "family": "VMware Local Security Checks", 
                "id": "103448"
            }
        ], 
        "Nessus": [
            {
                "name": "CentOS 4 : python (CESA-2011:0491)", 
                "file": "centos_RHSA-2011-0491.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "53814"
            }, 
            {
                "name": "CentOS 5 : python (CESA-2011:0492)", 
                "file": "centos_RHSA-2011-0492.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "53815"
            }, 
            {
                "name": "GLSA-201401-04 : Python: Multiple vulnerabilities", 
                "file": "gentoo_GLSA-201401-04.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "71811"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2010:215)", 
                "file": "mandriva_MDVSA-2010-215.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "50423"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2010:216)", 
                "file": "mandriva_MDVSA-2010-216.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "50424"
            }, 
            {
                "name": "Oracle Linux 4 : python (ELSA-2011-0491)", 
                "file": "oraclelinux_ELSA-2011-0491.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "68270"
            }, 
            {
                "name": "Oracle Linux 5 : python (ELSA-2011-0492)", 
                "file": "oraclelinux_ELSA-2011-0492.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "68271"
            }, 
            {
                "name": "RHEL 4 : python (RHSA-2011:0491)", 
                "file": "redhat-RHSA-2011-0491.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "53820"
            }, 
            {
                "name": "RHEL 5 : python (RHSA-2011:0492)", 
                "file": "redhat-RHSA-2011-0492.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "53821"
            }, 
            {
                "name": "RHEL 6 : python (RHSA-2011:0554)", 
                "file": "redhat-RHSA-2011-0554.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "54592"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL4.x, SL5.x i386/x86_64", 
                "file": "sl_20110505_python_on_SL4_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "61033"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL6.x i386/x86_64", 
                "file": "sl_20110519_python_on_SL6_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "61046"
            }, 
            {
                "name": "openSUSE Security Update : libpython2_6-1_0 (openSUSE-SU-2010:1049-1)", 
                "file": "suse_11_2_libpython2_6-1_0-101028.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "53756"
            }, 
            {
                "name": "openSUSE Security Update : libpython2_6-1_0 (openSUSE-SU-2010:1051-1)", 
                "file": "suse_11_3_libpython2_6-1_0-101028.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "75607"
            }, 
            {
                "name": "SuSE 11 Security Update : Python (SAT Patch Number 3491)", 
                "file": "suse_11_libpython2_6-1_0-101028.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "51134"
            }, 
            {
                "name": "SuSE 11.1 Security Update : Python (SAT Patch Number 3493)", 
                "file": "suse_11_libpython2_6-1_0-101109.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "51623"
            }, 
            {
                "name": "SuSE 10 Security Update : Python (ZYPP Patch Number 7314)", 
                "file": "suse_python-7314.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "51642"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 10.10 / 11.04 : python3.1, python3.2 vulnerabilities (USN-1314-1)", 
                "file": "ubuntu_USN-1314-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "57345"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 11.04 / 11.10 : python2.6 vulnerabilities (USN-1596-1)", 
                "file": "ubuntu_USN-1596-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62436"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.5 vulnerabilities (USN-1613-1)", 
                "file": "ubuntu_USN-1613-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62619"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.4 vulnerabilities (USN-1613-2)", 
                "file": "ubuntu_USN-1613-2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62620"
            }, 
            {
                "name": "VMSA-2012-0001 : VMware ESXi and ESX updates to third-party library and ESX Service Console", 
                "file": "vmware_VMSA-2012-0001.nasl", 
                "family": "VMware ESX Local Security Checks", 
                "id": "57749"
            }, 
            {
                "name": "VMware ESX / ESXi Service Console and Third-Party Libraries Multiple Vulnerabilities (VMSA-2012-0001) (remote check)", 
                "file": "vmware_VMSA-2012-0001_remote.nasl", 
                "family": "Misc.", 
                "id": "89105"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [
            {
                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215", 
                "id": "MDVSA-2010:215"
            }, 
            {
                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216", 
                "id": "MDVSA-2010:216"
            }
        ], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [
            {
                "url": "https://www.suse.com/security/cve/CVE-2010-3493.html", 
                "id": "SUSE-SR:2010:024"
            }, 
            {
                "url": "https://www.suse.com/security/cve/CVE-2010-3493.html", 
                "id": "SUSE-SR:2011:002"
            }
        ], 
        "Redhat": [
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110491", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0491.html", 
                    "id": "RHSA-2011:0491", 
                    "title": "RHSA-2011:0491: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=531697", 
                    "title": "CVE-2009-3720 expat: buffer over-read and crash on XML with malformed UTF-8 sequences", 
                    "id": "531697", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690", 
                    "title": "CVE-2010-1634 python: audioop: incorrect integer overflow checks", 
                    "id": "590690", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=598197", 
                    "title": "CVE-2010-2089 Python: Memory corruption in audioop module", 
                    "id": "598197", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110492", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0492.html", 
                    "id": "RHSA-2011:0492", 
                    "title": "RHSA-2011:0492: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=531697", 
                    "title": "CVE-2009-3720 expat: buffer over-read and crash on XML with malformed UTF-8 sequences", 
                    "id": "531697", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110554", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0554.html", 
                    "id": "RHSA-2011:0554", 
                    "title": "RHSA-2011:0554: python security, bug fix, and enhancement update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=603073", 
                    "title": "python >>> help() >>> modules command traceback when used without DISPLAY", 
                    "id": "603073", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=614680", 
                    "title": "Try to print repr() when a fatal garbage collection assertion fails", 
                    "id": "614680", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=625393", 
                    "title": "adjust test_commands unit test to the updated output of the ls command", 
                    "id": "625393", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=625395", 
                    "title": "include the tests/data directory in the python-test rpm", 
                    "id": "625395", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=626756", 
                    "title": "test_dbm fails on ppc64 & s390x", 
                    "id": "626756", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=627301", 
                    "title": "Rebase python from 2.6.5 to 2.6.6 in RHEL 6.1", 
                    "id": "627301", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=634944", 
                    "title": "rpmlint errors and warnings", 
                    "id": "634944", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=639392", 
                    "title": "Generating python backtrace with \"py-bt\" fails with a traceback", 
                    "id": "639392", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=649274", 
                    "title": "Infinite recursion in urllib2 on basicauth failure", 
                    "id": "649274", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=650588", 
                    "title": "subprocess fails in select when descriptors are large (rhel6)", 
                    "id": "650588", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=669847", 
                    "title": "urllib2's AbstractBasicAuthHandler is limited to 6 requests", 
                    "id": "669847", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=684991", 
                    "title": "python update causes rhythmbox to crash", 
                    "id": "684991", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690315", 
                    "title": "python occasionally fails to build on machines with more than one core", 
                    "id": "690315", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }
        ], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [
            {
                "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                "id": "USN-1596-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                "id": "USN-1613-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                "id": "USN-1613-2"
            }
        ], 
        "Debian": [], 
        "Vmware": []
    }
}