{
    "Information": {
        "Category": null, 
        "CAPEC": null, 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-4140", 
                "published": "2011-10-19T06:55:04.643-04:00", 
                "id": "CVE-2011-4140", 
                "modified": "2012-01-26T23:03:29.267-05:00", 
                "summary": "The CSRF protection mechanism in Django through 1.2.7 and 1.3.x through 1.3.1 does not properly handle web-server configurations supporting arbitrary HTTP Host headers, which allows remote attackers to trigger unauthenticated forged requests via vectors involving a DNS CNAME record and a web page containing JavaScript code."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/352.html", 
                "id": "CWE-352", 
                "title": "Cross-Site Request Forgery (CSRF)"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:djangoproject:django:1.2.3"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.1.0"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.2.4"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:0.91"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.3"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.2.1"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.2.2"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.0"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.2.5"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.1.2"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.2.6"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.1.3"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:0.96"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:0.95"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.0.2"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.0.1"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.3:alpha2"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:0.95.1"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.2.1:2"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.3:alpha1"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.1"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.2"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.59145", 
                "id": 59145
            }
        ], 
        "IAVM": [], 
        "BID": [], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "https://www.djangoproject.com/weblog/2011/sep/10/127/", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "https://www.djangoproject.com/weblog/2011/sep/09/", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=737366", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://openwall.com/lists/oss-security/2011/09/13/2", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://openwall.com/lists/oss-security/2011/09/11/1", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.debian.org/security/2011/dsa-2332", 
                    "vendor": "DEBIAN"
                }, 
                {
                    "url": "http://secunia.com/advisories/46614", 
                    "vendor": "SECUNIA"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "6.4", 
                    "access complexity": "medium", 
                    "confidentiality impact": "partial", 
                    "authentication": "none", 
                    "exploit": "8.6", 
                    "base": "6.8", 
                    "integrity impact": "partial", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2011-4140"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:15216", 
                "title": "DSA-2332-1 python-django -- several issues", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:15216"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "Debian Security Advisory DSA 2332-1 (python-django)", 
                "file": "deb_2332_1.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "70548"
            }
        ], 
        "Nessus": [
            {
                "name": "Debian DSA-2332-1 : python-django - several issues", 
                "file": "debian_DSA-2332.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "56671"
            }, 
            {
                "name": "openSUSE Security Update : python-django (openSUSE-SU-2012:0653-1)", 
                "file": "openSUSE-2012-294.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "74633"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [], 
        "Redhat": [], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [], 
        "Debian": [
            {
                "url": "https://security-tracker.debian.org/tracker/DSA-2332", 
                "id": "DSA-2332"
            }
        ], 
        "Vmware": []
    }
}