{
    "Information": {
        "Category": null, 
        "CAPEC": null, 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-1521", 
                "published": "2011-05-24T19:55:02.840-04:00", 
                "id": "CVE-2011-1521", 
                "modified": "2014-02-20T23:41:39.343-05:00", 
                "summary": "The urllib and urllib2 modules in Python 2.x before 2.7.2 and 3.x before 3.2.1 process Location headers that specify redirection to file: URLs, which makes it easier for remote attackers to obtain sensitive information or cause a denial of service (resource consumption) via a crafted URL, as demonstrated by the file:///etc/passwd and file:///dev/zero URLs."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/399.html", 
                "id": "CWE-399", 
                "title": "Resource Management Errors"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:python:python:2.0"
            }, 
            {
                "id": "cpe:/a:python:python:2.0.1"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.1"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.2"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.3"
            }, 
            {
                "id": "cpe:/a:python:python:3.0.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.7"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.7"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.5"
            }, 
            {
                "id": "cpe:/a:python:python:2.2.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.1.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.2.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.1.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.2.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.5"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.1.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.2"
            }, 
            {
                "id": "cpe:/a:python:python:3.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.7"
            }, 
            {
                "id": "cpe:/a:python:python:3.0"
            }, 
            {
                "id": "cpe:/a:python:python:2.5"
            }, 
            {
                "id": "cpe:/a:python:python:3.2:alpha"
            }, 
            {
                "id": "cpe:/a:python:python:3.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.2"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.57513", 
                "id": 57513
            }
        ], 
        "IAVM": [
            {
                "Disa key": "V0031252", 
                "id": "2012-A-0020", 
                "title": "Multiple Vulnerabilities in VMware ESX 4.1 and ESXi 4.1"
            }
        ], 
        "BID": [], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://hg.python.org/cpython/rev/b2934d98dac1/", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://hg.python.org/cpython/rev/96a6c128822b/", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://bugs.python.org/issue11662", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "https://www.djangoproject.com/weblog/2011/sep/10/127/", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "https://www.djangoproject.com/weblog/2011/sep/09/", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=737366", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1592-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2011:096", 
                    "vendor": "MANDRIVA"
                }, 
                {
                    "url": "http://support.apple.com/kb/HT5002", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://securitytracker.com/id?1025488", 
                    "vendor": "SECTRACK"
                }, 
                {
                    "url": "http://secunia.com/advisories/51040", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/51024", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/50858", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://openwall.com/lists/oss-security/2011/09/15/5", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://openwall.com/lists/oss-security/2011/09/13/2", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://openwall.com/lists/oss-security/2011/09/11/1", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://openwall.com/lists/oss-security/2011/03/28/2", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://openwall.com/lists/oss-security/2011/03/24/5", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2011-05/msg00005.html", 
                    "vendor": "SUSE"
                }, 
                {
                    "url": "http://lists.apple.com/archives/Security-announce/2011//Oct/msg00003.html", 
                    "vendor": "APPLE"
                }, 
                {
                    "url": "http://hg.python.org/cpython/file/b2934d98dac1/Misc/NEWS", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://hg.python.org/cpython/file/96a6c128822b/Misc/NEWS", 
                    "vendor": "CONFIRM"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "4.9", 
                    "access complexity": "low", 
                    "confidentiality impact": "partial", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "6.4", 
                    "integrity impact": "none", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2011-1521"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:17830", 
                "title": "USN-1613-1 -- python2.5 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:17830"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:23229", 
                "title": "ELSA-2011:0492: python security update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:23229"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28060", 
                "title": "DEPRECATED: ELSA-2011-0492 -- python security update (moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28060"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28032", 
                "title": "DEPRECATED: ELSA-2011-0554 -- python security, bug fix, and enhancement update (moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28032"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:23473", 
                "title": "ELSA-2011:0554: python security, bug fix, and enhancement update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:23473"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18020", 
                "title": "USN-1613-2 -- python2.4 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18020"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21923", 
                "title": "RHSA-2011:0492: python security update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21923"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21626", 
                "title": "RHSA-2011:0554: python security, bug fix, and enhancement update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21626"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:20200", 
                "title": "VMware ESXi and ESX updates to third party library and ESX Service Console", 
                "class": "vulnerability", 
                "id": "oval:org.mitre.oval:def:20200"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:15345", 
                "title": "USN-1314-1 -- Python 3 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:15345"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:17976", 
                "title": "USN-1592-1 -- python2.7 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:17976"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18043", 
                "title": "USN-1596-1 -- python2.6 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18043"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "CentOS Update for python CESA-2011:0491 centos4 i386", 
                "file": "gb_CESA-2011_0491_python_centos4_i386.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "880556"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0491 centos4 x86_64", 
                "file": "gb_CESA-2011_0491_python_centos4_x86_64.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "881427"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0492 centos5 i386", 
                "file": "gb_CESA-2011_0492_python_centos5_i386.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "880500"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0492 centos5 x86_64", 
                "file": "gb_CESA-2011_0492_python_centos5_x86_64.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "881282"
            }, 
            {
                "name": "Mac OS X v10.6.8 Multiple Vulnerabilities (2011-006)", 
                "file": "gb_macosx_su11-006.nasl", 
                "family": "Mac OS X Local Security Checks", 
                "id": "802336"
            }, 
            {
                "name": "Mandriva Update for python MDVSA-2011:096 (python)", 
                "file": "gb_mandriva_MDVSA_2011_096.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "831403"
            }, 
            {
                "name": "Python Multiple Vulnerabilities (Windows)", 
                "file": "gb_python_mult_vuln_win.nasl", 
                "family": "General", 
                "id": "801797"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0491-01", 
                "file": "gb_RHSA-2011_0491-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870430"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0492-01", 
                "file": "gb_RHSA-2011_0492-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870428"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0554-01", 
                "file": "gb_RHSA-2011_0554-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870597"
            }, 
            {
                "name": "Ubuntu Update for python3.1 USN-1314-1", 
                "file": "gb_ubuntu_USN_1314_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "840852"
            }, 
            {
                "name": "Ubuntu Update for python2.7 USN-1592-1", 
                "file": "gb_ubuntu_USN_1592_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841173"
            }, 
            {
                "name": "Ubuntu Update for python2.6 USN-1596-1", 
                "file": "gb_ubuntu_USN_1596_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841178"
            }, 
            {
                "name": "Ubuntu Update for python2.5 USN-1613-1", 
                "file": "gb_ubuntu_USN_1613_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841195"
            }, 
            {
                "name": "Ubuntu Update for python2.4 USN-1613-2", 
                "file": "gb_ubuntu_USN_1613_2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841194"
            }, 
            {
                "name": "VMSA-2012-0001 VMware ESXi and ESX updates to third party library and ESX Service Console", 
                "file": "gb_VMSA-2012-0001.nasl", 
                "family": "VMware Local Security Checks", 
                "id": "103448"
            }
        ], 
        "Nessus": [
            {
                "name": "CentOS 4 : python (CESA-2011:0491)", 
                "file": "centos_RHSA-2011-0491.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "53814"
            }, 
            {
                "name": "CentOS 5 : python (CESA-2011:0492)", 
                "file": "centos_RHSA-2011-0492.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "53815"
            }, 
            {
                "name": "Mac OS X 10.7 < 10.7.2", 
                "file": "macosx_10_7_2.nasl", 
                "family": "MacOS X Local Security Checks", 
                "id": "56480"
            }, 
            {
                "name": "Mac OS X Multiple Vulnerabilities (Security Update 2011-006)", 
                "file": "macosx_SecUpd2011-006.nasl", 
                "family": "MacOS X Local Security Checks", 
                "id": "56481"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2011:096)", 
                "file": "mandriva_MDVSA-2011-096.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "54611"
            }, 
            {
                "name": "Oracle Linux 4 : python (ELSA-2011-0491)", 
                "file": "oraclelinux_ELSA-2011-0491.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "68270"
            }, 
            {
                "name": "Oracle Linux 5 : python (ELSA-2011-0492)", 
                "file": "oraclelinux_ELSA-2011-0492.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "68271"
            }, 
            {
                "name": "RHEL 4 : python (RHSA-2011:0491)", 
                "file": "redhat-RHSA-2011-0491.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "53820"
            }, 
            {
                "name": "RHEL 5 : python (RHSA-2011:0492)", 
                "file": "redhat-RHSA-2011-0492.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "53821"
            }, 
            {
                "name": "RHEL 6 : python (RHSA-2011:0554)", 
                "file": "redhat-RHSA-2011-0554.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "54592"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL4.x, SL5.x i386/x86_64", 
                "file": "sl_20110505_python_on_SL4_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "61033"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL6.x i386/x86_64", 
                "file": "sl_20110519_python_on_SL6_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "61046"
            }, 
            {
                "name": "openSUSE Security Update : libpython2_6-1_0 (openSUSE-SU-2011:0484-1)", 
                "file": "suse_11_2_libpython2_6-1_0-110506.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "53885"
            }, 
            {
                "name": "openSUSE Security Update : libpython2_6-1_0 (openSUSE-SU-2011:0484-1)", 
                "file": "suse_11_3_libpython2_6-1_0-110506.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "75608"
            }, 
            {
                "name": "openSUSE Security Update : libpython2_6-1_0 (openSUSE-SU-2011:0484-1)", 
                "file": "suse_11_4_libpython2_6-1_0-110506.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "75916"
            }, 
            {
                "name": "SuSE 11.1 Security Update : Python (SAT Patch Number 4512)", 
                "file": "suse_11_libpython2_6-1_0-110506.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "54641"
            }, 
            {
                "name": "SuSE 11.1 Security Update : libpython2_6-1_0, libpython2_6-1_0-32bit, libpython2_6-1_0-x86, python, etc (SAT Patch Number 6310)", 
                "file": "suse_11_python-randomisation-update-120516.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "64220"
            }, 
            {
                "name": "SuSE 11.1 Security Update : libpython2_6-1_0, libpython2_6-1_0-32bit, libpython2_6-1_0-x86, python, etc (SAT Patch Number 6310)", 
                "file": "suse_11_python-randomisation-update-120517.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "64221"
            }, 
            {
                "name": "SuSE 10 Security Update : python (ZYPP Patch Number 7506)", 
                "file": "suse_python-7506.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "57248"
            }, 
            {
                "name": "SuSE 10 Security Update : python (ZYPP Patch Number 7509)", 
                "file": "suse_python-7509.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "54643"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 10.10 / 11.04 : python3.1, python3.2 vulnerabilities (USN-1314-1)", 
                "file": "ubuntu_USN-1314-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "57345"
            }, 
            {
                "name": "Ubuntu 11.04 / 11.10 : python2.7 vulnerabilities (USN-1592-1)", 
                "file": "ubuntu_USN-1592-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62410"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 11.04 / 11.10 : python2.6 vulnerabilities (USN-1596-1)", 
                "file": "ubuntu_USN-1596-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62436"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.5 vulnerabilities (USN-1613-1)", 
                "file": "ubuntu_USN-1613-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62619"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.4 vulnerabilities (USN-1613-2)", 
                "file": "ubuntu_USN-1613-2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62620"
            }, 
            {
                "name": "ESXi 5.0 < Build 608089 Multiple Vulnerabilities (remote check)", 
                "file": "vmware_esxi_5_0_build_608089_remote.nasl", 
                "family": "Misc.", 
                "id": "70881"
            }, 
            {
                "name": "VMSA-2012-0001 : VMware ESXi and ESX updates to third-party library and ESX Service Console", 
                "file": "vmware_VMSA-2012-0001.nasl", 
                "family": "VMware ESX Local Security Checks", 
                "id": "57749"
            }, 
            {
                "name": "VMware ESX / ESXi Service Console and Third-Party Libraries Multiple Vulnerabilities (VMSA-2012-0001) (remote check)", 
                "file": "vmware_VMSA-2012-0001_remote.nasl", 
                "family": "Misc.", 
                "id": "89105"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [
            {
                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2011:096", 
                "id": "MDVSA-2011:096"
            }
        ], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [
            {
                "url": "https://www.suse.com/security/cve/CVE-2011-1521.html", 
                "id": "SUSE-SR:2011:009"
            }
        ], 
        "Redhat": [
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110491", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0491.html", 
                    "id": "RHSA-2011:0491", 
                    "title": "RHSA-2011:0491: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=531697", 
                    "title": "CVE-2009-3720 expat: buffer over-read and crash on XML with malformed UTF-8 sequences", 
                    "id": "531697", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690", 
                    "title": "CVE-2010-1634 python: audioop: incorrect integer overflow checks", 
                    "id": "590690", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=598197", 
                    "title": "CVE-2010-2089 Python: Memory corruption in audioop module", 
                    "id": "598197", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110492", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0492.html", 
                    "id": "RHSA-2011:0492", 
                    "title": "RHSA-2011:0492: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=531697", 
                    "title": "CVE-2009-3720 expat: buffer over-read and crash on XML with malformed UTF-8 sequences", 
                    "id": "531697", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110554", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0554.html", 
                    "id": "RHSA-2011:0554", 
                    "title": "RHSA-2011:0554: python security, bug fix, and enhancement update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=603073", 
                    "title": "python >>> help() >>> modules command traceback when used without DISPLAY", 
                    "id": "603073", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=614680", 
                    "title": "Try to print repr() when a fatal garbage collection assertion fails", 
                    "id": "614680", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=625393", 
                    "title": "adjust test_commands unit test to the updated output of the ls command", 
                    "id": "625393", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=625395", 
                    "title": "include the tests/data directory in the python-test rpm", 
                    "id": "625395", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=626756", 
                    "title": "test_dbm fails on ppc64 & s390x", 
                    "id": "626756", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=627301", 
                    "title": "Rebase python from 2.6.5 to 2.6.6 in RHEL 6.1", 
                    "id": "627301", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=634944", 
                    "title": "rpmlint errors and warnings", 
                    "id": "634944", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=639392", 
                    "title": "Generating python backtrace with \"py-bt\" fails with a traceback", 
                    "id": "639392", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=649274", 
                    "title": "Infinite recursion in urllib2 on basicauth failure", 
                    "id": "649274", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=650588", 
                    "title": "subprocess fails in select when descriptors are large (rhel6)", 
                    "id": "650588", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=669847", 
                    "title": "urllib2's AbstractBasicAuthHandler is limited to 6 requests", 
                    "id": "669847", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=684991", 
                    "title": "python update causes rhythmbox to crash", 
                    "id": "684991", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690315", 
                    "title": "python occasionally fails to build on machines with more than one core", 
                    "id": "690315", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }
        ], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [
            {
                "url": "http://www.ubuntu.com/usn/USN-1592-1", 
                "id": "USN-1592-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                "id": "USN-1596-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                "id": "USN-1613-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                "id": "USN-1613-2"
            }
        ], 
        "Debian": [], 
        "Vmware": []
    }
}