{
    "Information": {
        "Category": null, 
        "CAPEC": null, 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-3492", 
                "published": "2010-10-19T16:00:04.237-04:00", 
                "id": "CVE-2010-3492", 
                "modified": "2011-07-18T22:40:07.127-04:00", 
                "summary": "The asyncore module in Python before 3.2 does not properly handle unsuccessful calls to the accept function, and does not have accompanying documentation describing how daemon applications should handle unsuccessful calls to the accept function, which makes it easier for remote attackers to conduct denial of service attacks that terminate these applications via network connections."
            }
        ], 
        "CWE": null, 
        "CPE": [
            {
                "id": "cpe:/a:python:python:2.0"
            }, 
            {
                "id": "cpe:/a:python:python:2.0.1"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.1"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.2"
            }, 
            {
                "id": "cpe:/a:python:python:3.0.1"
            }, 
            {
                "id": "cpe:/a:python:python:0.9.0"
            }, 
            {
                "id": "cpe:/a:python:python:0.9.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.7"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.3"
            }, 
            {
                "id": "cpe:/a:python:python:1.6.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.2.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.1.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.2.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.1.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.2.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.5"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.1.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.3.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.3"
            }, 
            {
                "id": "cpe:/a:python:python:1.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.1"
            }, 
            {
                "id": "cpe:/a:python:python:1.2"
            }, 
            {
                "id": "cpe:/a:python:python:1.5.2"
            }, 
            {
                "id": "cpe:/a:python:python:1.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.7"
            }, 
            {
                "id": "cpe:/a:python:python:2.5"
            }, 
            {
                "id": "cpe:/a:python:python:3.0"
            }, 
            {
                "id": "cpe:/a:python:python:2.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.4.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.2"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.55128", 
                "id": 55128
            }
        ], 
        "IAVM": [], 
        "BID": [], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "http://bugs.python.org/issue6706", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/24/3", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/22/3", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/11/2", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2010/09/09/6", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216", 
                    "vendor": "MANDRIVA"
                }, 
                {
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215", 
                    "vendor": "MANDRIVA"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "2.9", 
                    "access complexity": "low", 
                    "confidentiality impact": "none", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "5.0", 
                    "integrity impact": "none", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2010-3492"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:12111", 
                "title": "Vulnerability in the asyncore module in Python before 3.2", 
                "class": "vulnerability", 
                "id": "oval:org.mitre.oval:def:12111"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "Mandriva Update for python MDVSA-2010:215 (python)", 
                "file": "gb_mandriva_MDVSA_2010_215.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "831224"
            }, 
            {
                "name": "Mandriva Update for python MDVSA-2010:216 (python)", 
                "file": "gb_mandriva_MDVSA_2010_216.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "831233"
            }
        ], 
        "Nessus": [
            {
                "name": "GLSA-201401-04 : Python: Multiple vulnerabilities", 
                "file": "gentoo_GLSA-201401-04.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "71811"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2010:215)", 
                "file": "mandriva_MDVSA-2010-215.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "50423"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2010:216)", 
                "file": "mandriva_MDVSA-2010-216.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "50424"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [
            {
                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215", 
                "id": "MDVSA-2010:215"
            }, 
            {
                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216", 
                "id": "MDVSA-2010:216"
            }
        ], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [], 
        "Redhat": [], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [], 
        "Debian": [], 
        "Vmware": []
    }
}