{
    "Information": {
        "Category": null, 
        "CAPEC": null, 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-7185", 
                "published": "2014-10-08T13:55:05.187-04:00", 
                "id": "CVE-2014-7185", 
                "modified": "2016-03-30T18:00:32.423-04:00", 
                "summary": "Integer overflow in bufferobject.c in Python before 2.7.8 allows context-dependent attackers to obtain sensitive information from process memory via a large size and offset in a \"buffer\" function."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/189.html", 
                "id": "CWE-189", 
                "title": "Numeric Errors"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/o:apple:mac_os_x:10.10.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.5"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.1150"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.1150::~~~~x64~"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.2150"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.2:rc1"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.7"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.1:rc1"
            }, 
            {
                "id": "cpe:/a:python:python:2.7"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.71877", 
                "id": 71877
            }
        ], 
        "IAVM": [], 
        "BID": [
            {
                "url": "http://www.securityfocus.com/bid/70089", 
                "id": 70089
            }
        ], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "https://support.apple.com/kb/HT205031", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1146026", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://xforce.iss.net/xforce/xfdb/96193", 
                    "vendor": "XF"
                }, 
                {
                    "url": "http://www.securityfocus.com/bid/70089", 
                    "vendor": "BID"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2014/09/25/47", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2014/09/23/5", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-updates/2014-10/msg00016.html", 
                    "vendor": "SUSE"
                }, 
                {
                    "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-October/139663.html", 
                    "vendor": "FEDORA"
                }, 
                {
                    "url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html", 
                    "vendor": "APPLE"
                }, 
                {
                    "url": "http://bugs.python.org/issue21831", 
                    "vendor": "CONFIRM"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "4.9", 
                    "access complexity": "low", 
                    "confidentiality impact": "partial", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "6.4", 
                    "integrity impact": "none", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2014-7185"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28365", 
                "title": "SUSE-SU-2014:1518-1 -- Security update for Python (moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28365"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:27540", 
                "title": "SUSE-SU-2014:1511-1 -- Security update for python, python-base, python-doc (moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:27540"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "Python Integer Overflow Vulnerability - 01 Oct14 (Windows)", 
                "file": "gb_python_integer_overflow_vuln_oct14_win.nasl", 
                "family": "General", 
                "id": "800052"
            }
        ], 
        "Nessus": [
            {
                "name": "Amazon Linux AMI : python27 (ALAS-2014-440)", 
                "file": "ala_ALAS-2014-440.nasl", 
                "family": "Amazon Linux Local Security Checks", 
                "id": "78873"
            }, 
            {
                "name": "Amazon Linux AMI : python26 (ALAS-2015-621)", 
                "file": "ala_ALAS-2015-621.nasl", 
                "family": "Amazon Linux Local Security Checks", 
                "id": "87347"
            }, 
            {
                "name": "CentOS 6 : python (CESA-2015:1330)", 
                "file": "centos_RHSA-2015-1330.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "85012"
            }, 
            {
                "name": "CentOS 7 : python (CESA-2015:2101)", 
                "file": "centos_RHSA-2015-2101.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "87129"
            }, 
            {
                "name": "Fedora 19 : python-2.7.5-14.fc19 (2014-11522)", 
                "file": "fedora_2014-11522.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "78703"
            }, 
            {
                "name": "Fedora 20 : python-2.7.5-14.fc20 (2014-11559)", 
                "file": "fedora_2014-11559.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "77998"
            }, 
            {
                "name": "GLSA-201503-10 : Python: Multiple vulnerabilities", 
                "file": "gentoo_GLSA-201503-10.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "82009"
            }, 
            {
                "name": "Mac OS X < 10.10.5 Multiple Vulnerabilities", 
                "file": "macosx_10_10_5.nasl", 
                "family": "MacOS X Local Security Checks", 
                "id": "85408"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2014:197)", 
                "file": "mandriva_MDVSA-2014-197.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "78613"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2015:075)", 
                "file": "mandriva_MDVSA-2015-075.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "82328"
            }, 
            {
                "name": "openSUSE Security Update : python (openSUSE-SU-2014:1292-1)", 
                "file": "openSUSE-2014-588.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "78453"
            }, 
            {
                "name": "Oracle Linux 6 : python (ELSA-2015-1330)", 
                "file": "oraclelinux_ELSA-2015-1330.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "85099"
            }, 
            {
                "name": "Oracle Linux 7 : python (ELSA-2015-2101)", 
                "file": "oraclelinux_ELSA-2015-2101.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "87020"
            }, 
            {
                "name": "OracleVM 3.3 : python (OVMSA-2015-0098)", 
                "file": "oraclevm_OVMSA-2015-0098.nasl", 
                "family": "OracleVM Local Security Checks", 
                "id": "85139"
            }, 
            {
                "name": "RHEL 6 : python (RHSA-2015:1330)", 
                "file": "redhat-RHSA-2015-1330.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "84938"
            }, 
            {
                "name": "RHEL 7 : python (RHSA-2015:2101)", 
                "file": "redhat-RHSA-2015-2101.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "86968"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL6.x i386/x86_64", 
                "file": "sl_20150722_python_on_SL6_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "85206"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL7.x x86_64", 
                "file": "sl_20151119_python_on_SL7_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "87570"
            }, 
            {
                "name": "Oracle Solaris Third-Party Patch Update : python (cve_2014_7185_integer_overflow)", 
                "file": "solaris11_python_20141120.nasl", 
                "family": "Solaris Local Security Checks", 
                "id": "80750"
            }, 
            {
                "name": "SuSE 11.3 Security Update : Python (SAT Patch Number 9996)", 
                "file": "suse_11_python-2014-11-19-141119.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "79619"
            }, 
            {
                "name": "SUSE SLED12 / SLES12 Security Update : python, python-base, python-doc (SUSE-SU-2014:1511-1)", 
                "file": "suse_SU-2014-1511-1.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "83646"
            }, 
            {
                "name": "SUSE SLED12 / SLES12 Security Update : python (SUSE-SU-2015:1344-1)", 
                "file": "suse_SU-2015-1344-1.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "85250"
            }, 
            {
                "name": "Ubuntu 12.04 LTS / 14.04 / 14.10 : python2.7, python3.2, python3.4 vulnerabilities (USN-2653-1)", 
                "file": "ubuntu_USN-2653-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "84428"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [
            {
                "url": "https://admin.fedoraproject.org/updates/FEDORA-2014-11559", 
                "id": "FEDORA-2014-11559"
            }
        ], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [
            {
                "url": "https://www.suse.com/security/cve/CVE-2014-7185.html", 
                "id": "openSUSE-SU-2014:1292"
            }
        ], 
        "Redhat": [
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20151330", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2015-1330.html", 
                    "id": "RHSA-2015:1330", 
                    "title": "RHSA-2015:1330: python security, bug fix, and enhancement update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=794632", 
                    "title": "Python 2.6 installation is not 64 bit clean", 
                    "id": "794632", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1046174", 
                    "title": "CVE-2013-1752 python: multiple unbound readline() DoS flaws in python stdlib", 
                    "id": "1046174", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062370", 
                    "title": "CVE-2014-1912 python: buffer overflow in socket.recvfrom_into()", 
                    "id": "1062370", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1073165", 
                    "title": "subprocess.Popen.communicate() fails with: IOError: [Errno 4] Interrupted system call", 
                    "id": "1073165", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1113527", 
                    "title": "CVE-2014-4650 python: CGIHTTPServer module does not properly handle URL-encoded path separators in URLs", 
                    "id": "1113527", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1146026", 
                    "title": "CVE-2014-7185 python: buffer() integer overflow leading to out of bounds read", 
                    "id": "1146026", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1160640", 
                    "title": "cProfile main() traceback if options syntax is invalid", 
                    "id": "1160640", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1180864", 
                    "title": "multiprocessing BaseManager serve_client() does not check EINTR on recv", 
                    "id": "1180864", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1199997", 
                    "title": "python-libs should have \"Provides: python-ordereddict\"", 
                    "id": "1199997", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1223037", 
                    "title": "Python raises exception on deepcopy of instance methods", 
                    "id": "1223037", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20152101", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2015-2101.html", 
                    "id": "RHSA-2015:2101", 
                    "title": "RHSA-2015:2101: python security, bug fix, and enhancement update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1046170", 
                    "title": "CVE-2013-1753 python: XMLRPC library unrestricted decompression of HTTP responses using gzip enconding", 
                    "id": "1046170", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1046174", 
                    "title": "CVE-2013-1752 python: multiple unbound readline() DoS flaws in python stdlib", 
                    "id": "1046174", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1058482", 
                    "title": "tmpwatch removes python multiprocessing sockets", 
                    "id": "1058482", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1112285", 
                    "title": "CVE-2014-4616 python: missing boundary check in JSON module", 
                    "id": "1112285", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1113527", 
                    "title": "CVE-2014-4650 python: CGIHTTPServer module does not properly handle URL-encoded path separators in URLs", 
                    "id": "1113527", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1146026", 
                    "title": "CVE-2014-7185 python: buffer() integer overflow leading to out of bounds read", 
                    "id": "1146026", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1173041", 
                    "title": "CVE-2014-9365 python: failure to validate certificates in the HTTP client with TLS (PEP 476)", 
                    "id": "1173041", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1177613", 
                    "title": "setup.py bdist_rpm NameError: global name 'get_python_version' is not defined", 
                    "id": "1177613", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1181624", 
                    "title": "multiprocessing BaseManager serve_client() does not check EINTR on recv", 
                    "id": "1181624", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1237107", 
                    "title": "cProfile main() traceback if options syntax is invalid", 
                    "id": "1237107", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1250611", 
                    "title": "SSLContext.load_cert_chain() keyfile argument can't be set to None", 
                    "id": "1250611", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1259421", 
                    "title": "Backport SSLSocket.version() to python 2.7.5", 
                    "id": "1259421", 
                    "issue date": "2015-06-25", 
                    "associated redhat": "RHSA-2015:2101"
                }
            }
        ], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [], 
        "Debian": [], 
        "Vmware": []
    }
}